package pojos;
// Generated May 11, 2016 10:47:41 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Kerdesek generated by hbm2java
 */
@Entity
@Table(name="kerdesek"
    ,catalog="java_vizsga"
)
public class Kerdesek  implements java.io.Serializable {


     private Integer idkerdesek;
     private String kerdes;
     private String valasz0;
     private String valasz1;
     private String valasz2;
     private String valasz3;
     private int helyesvalasz;

    public Kerdesek() {
    }

    public Kerdesek(String kerdes, String valasz0, String valasz1, String valasz2, String valasz3, int helyesvalasz) {
       this.kerdes = kerdes;
       this.valasz0 = valasz0;
       this.valasz1 = valasz1;
       this.valasz2 = valasz2;
       this.valasz3 = valasz3;
       this.helyesvalasz = helyesvalasz;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idkerdesek", unique=true, nullable=false)
    public Integer getIdkerdesek() {
        return this.idkerdesek;
    }
    
    public void setIdkerdesek(Integer idkerdesek) {
        this.idkerdesek = idkerdesek;
    }

    
    @Column(name="kerdes", nullable=false, length=200)
    public String getKerdes() {
        return this.kerdes;
    }
    
    public void setKerdes(String kerdes) {
        this.kerdes = kerdes;
    }

    
    @Column(name="valasz0", nullable=false, length=200)
    public String getValasz0() {
        return this.valasz0;
    }
    
    public void setValasz0(String valasz0) {
        this.valasz0 = valasz0;
    }

    
    @Column(name="valasz1", nullable=false, length=200)
    public String getValasz1() {
        return this.valasz1;
    }
    
    public void setValasz1(String valasz1) {
        this.valasz1 = valasz1;
    }

    
    @Column(name="valasz2", nullable=false, length=200)
    public String getValasz2() {
        return this.valasz2;
    }
    
    public void setValasz2(String valasz2) {
        this.valasz2 = valasz2;
    }

    
    @Column(name="valasz3", nullable=false, length=200)
    public String getValasz3() {
        return this.valasz3;
    }
    
    public void setValasz3(String valasz3) {
        this.valasz3 = valasz3;
    }

    
    @Column(name="helyesvalasz", nullable=false)
    public int getHelyesvalasz() {
        return this.helyesvalasz;
    }
    
    public void setHelyesvalasz(int helyesvalasz) {
        this.helyesvalasz = helyesvalasz;
    }




}


